name: build

on:
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: 'true'

      # - uses: actions/download-artifact@v1
      #   with:
      #     name: jar
      #     path: .

      - name: Cache GraalVM
        uses: actions/cache@v1
        id: cache-graalvm
        with:
          path: ~/graalvm-ce-java11-22.0.0.2
          key: ${{ runner.os }}-graalvm-22.0.0.2
          restore-keys: |
                ${{ runner.os }}-graalvm-22.0.0.2

      - name: Download Deps
        run: |
          scripts/download-deps

      - name: Download GraalVM
        run: |
          cd ~
          if ! [ -d graalvm-ce-java11-22.0.0.2 ]; then
            curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-darwin-amd64-22.0.0.2.tar.gz
            tar xzf graalvm-ce-java11-darwin-amd64-22.0.0.2.tar.gz
          fi

      - name: Build macOS native image
        run: |
          export GRAALVM_HOME="$HOME/graalvm-ce-java11-22.0.0.2/Contents/Home"
          scripts/compile-shared

      # - uses: actions/upload-artifact@v1
      #   with:
      #     path: bb
      #     name: babashka-${{ steps.babashka-version.outputs.version }}-macos-amd64.zip


